from typing import List


def contains_duplicate(nums: List[int]) -> bool: ...
def count_bits(n: int) -> List[int]: ...
def h_index(citations: List[int]) -> int: ...
def letter_combinations(digits: str) -> List[str]: ...
def max_area(height: List[int]) -> int: ...
def max_product(nums: List[int]) -> int: ...
def max_subarray(nums: List[int]) -> int: ...
def min_cost_connect_points(points: List[List[int]]) -> int: ...
